language: node_js

os:
  - linux
  - osx

node_js:
  - 6
  - 8
  - 10

before_install:
  - npm install -g grunt-cli

install:
  - npm install
  - lerna bootstrap

script:
  - grunt test

after_success:
  - npm run coveralls
